### ISSUE TITLE
适配emlog pro

### ISSUE THREAD

**Issue by bzmshang** [kannafay/ifalse#4]
主题很漂亮，真心很喜欢
emlog pro中有个跟你这个一样的
但好像有些bug
不知道作者有没有考虑亲自适配下emlog pro的

**Comment by kannafay** [comment]
emlog是另外一个开发者移植的，迁移的版本有点旧了。
我暂时还没有将iFalse主题移植到emlog的想法。

**Comment by kannafay** [comment]
你可以试试wordpress
